### ISSUE TITLE
Is it necessary to enable "Parity Mode" for most builds?

### ISSUE THREAD

**Issue by kumasento** [custom-computing-ic/dfe-snippets#8]
The `setDRAMFreq` function in `ManagerUtils` uses `setEnableParityMode` for every MAIA build. I am just wondering whether it is necessary and what the benefit could we get.

Thanks

**Comment by paul-g** [comment]
I think it was required in previous compiler versions for Max4. It seems to be deprecated in 2016.1 so it might not be necessary anymore.

**Comment by kumasento** [comment]
Is it also the reason for us to use `setMAX4qMode` and `setDataReadFIFOExtraPipelineRegInFabric`?

**Comment by paul-g** [comment]
Yes. The latter is to improve timing in principle, though I m not convinced
it helps in all cases.

**Comment by kumasento** [comment]
Cool, let me experiment on that then. Cheers!
